apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django-react-app
  labels:
    app: backend  
spec:
   replicas: 2
   selector:
    matchLabels:
      app: backend
   template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: django-container        
          image: gerrome/django-react-app_backend:5
          imagePullPolicy: Always             
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user          
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pgdb:5432/$(POSTGRES_DB) 
          command: ["sh", "/wsgi-entrypoint.sh"]    
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-react-app  
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
