apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: django-react-app
type: Opaque
data: 
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  postgres-db: cmVhbGVzdF9lc3RhdGU=
