apiVersion: v1
kind: Service 
metadata:
  name: mongodb
  namespace: mern-stack
  labels:
    app: mongodb
spec:
   selector:
      app: mongodb
   ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: mern-stack  
  labels:
    app: mongodb
spec:
   serviceName: mongodb 
   replicas: 1
   selector:
    matchLabels:
      app: mongodb
   template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: gerrome/mern-stack-app_mongo:2.3
          imagePullPolicy: Always
          ports: 
            - containerPort: 27017
          #command: ["sh", "/init.sh"]  
          env:
            - name: MONGO_INITDB_DATABASE
              value: "basic-mern-app"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: p-vc
              mountPath: /data/mydb
   volumeClaimTemplates:
      - metadata:
          name: p-vc
        spec: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      