 apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: MongoDBStatefulSet
  labels:
    app: mongodb  
spec:
   serviceName: MongoService 
   replicas: 1
   selector:
    matchLabels:
      app: mongodb
   template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports: 
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: MongoSecret
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: MongoSecret
                  key: password
          volumeMounts:
            - name: pvc
              mountPath: /data/db
   volumeClaimTemplates:
      - metadata:
          name: pvc
        spec: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: Service 
metadata:
  name: MongoService
spec:
   selector:
      app: mongodb
   ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432      