apiVersion: v1
kind: Service 
metadata:
  name: mongodb
  namespace: mern-stack
  labels:
    app: mongodb
spec:
   selector:
      app: mongodb
   ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: mern-stack  
  labels:
    app: mongodb
spec:
   serviceName: mongodb 
   replicas: 1
   selector:
    matchLabels:
      app: mongodb
   template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:4.4
          ports: 
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: pvc
              mountPath: /data/db
   volumeClaimTemplates:
      - metadata:
          name: pvc
        spec: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      