apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeExpress
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gerrome/mern-stack-app_server:1
        ports:
        - containerPort: 5000       
---
apiVersion: v1
kind: Service
metadata:
  name: DjangoService
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000