apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-deployment
  namespace: mern-stack  
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: node-express-container
        image: gerrome/mern-stack-app_server:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password         
  #        - name: DATABASE_URL
  #          value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb:27017      
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: mern-stack  
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 5000