apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-deployment
  namespace: django-vuejs  
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: vuejs-container
        image: gerrome/django-vuejs_app:3
        imagePullPolicy: Always          
        ports:
          - containerPort: 80               
---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-service
  namespace: django-vuejs  
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 80