apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: java-container
        image: gerrome/java-angular-stack_backend:1
        ports:
        - containerPort: 8080
        env:                
          - name: MYSQL_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysqlSecret
                key: user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlSecret
                key: password      
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080