apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-deployment
  namespace: mevn-stack  
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: vuejs-container
        image: gerrome/mevn-stack-app_client:1      
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-service
  namespace: mevn-stack  
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 80