apiVersion: v1
kind: Service 
metadata:
  name: mysql
  namespace: php-react-mysql
  labels:
    app: mysql  
spec:
   selector:
      app: mysql
   ports:
      - protocol: TCP
        port: 3306
        targetPort: 3306
---
apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mysql-statefulset
  namespace: php-react-mysql  
spec:
   serviceName: mysql
   replicas: 1
   selector:
    matchLabels:
      app: mysql
   template:
    metadata:
      labels:
        app: mysql
        selector: mysql
    spec:
      containers:
        - name: mysql-container
          image: gerrome/php-react-mysql_db:1.2
          ports: 
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - name: pvc
              mountPath: /data/db
   volumeClaimTemplates:
      - metadata:
          name: pvc
        spec: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
