apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: php-react-mysql
  labels:
    app: backend  
spec:
   replicas: 2
   selector:
    matchLabels:
      app: backend
   template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: php-container        
          image: gerrome/php-react-mysql_backend:1.5
          imagePullPolicy: Always             
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password         
            - name: DATABASE_URL
              value: mysql://root:root@mysql:33060/react-crud          
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: php-react-mysql 
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
