apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeExpress
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gerrome/pern-stack_server:1
        ports:
        - containerPort: 5000
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres-password
          - name: POSTGRES_DB
            value: postgres
          - name: DATABASE_URL
            value: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}        
---
apiVersion: v1
kind: Service
metadata:
  name: NodeExpressService
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 5000