apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: pern-stack
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gerrome/pern-stack_server:1
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-db
          - name: DATABASE_URL
            value: postgresql://postgres:5432/PERN-Starter    
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: pern-stack  
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 3000