apiVersion: v1
kind: Service 
metadata:
  name: postgresql
  namespace: pern-stack
  labels:
    app: postgresql  
spec:
   selector:
      app: postgresql
   ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432       

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: pern-stack  
spec:
   serviceName: postgresql 
   replicas: 1
   selector:
    matchLabels:
      app: postgresql
   template:
    metadata:
      labels:
        app: postgresql
        selector: postgresql
    spec:
      containers:
        - name: postgres-container
          image: postgres:10.1-alpine
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
          volumeMounts:
            - name: pvc
              mountPath: /data/db
   volumeClaimTemplates:
      - metadata:
          name: pvc
        spec: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
