apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pern-stack  
type: Opaque
data: 
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  postgres-db: UEVSTi1TdGFydGVy